name: captable
services:
  app:
    build:
      target: deps
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: captable-app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ".env"
    working_dir: /app
    command: [/bin/sh, -c, "pnpm install && pnpm dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/.pnpm-store

  studio:
    build:
      target: deps
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: captable-studio
    restart: always
    ports:
      - 5555:5555
    env_file:
      - ".env"
    working_dir: /app
    command: [/bin/sh, -c, "pnpm install && pnpm db:studio"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/.pnpm-store
